window.APP_DATA = {
  "title": "Checklist VN (theo chủ đề)",
  "sections": [
    {
      "id": "food",
      "emoji": "🍜",
      "name": "Ăn uống",
      "hint": "Món ăn / đồ uống muốn thử",
      "items": [
        "bún riêu cua 15 Hàng Cót (thêm trứng vịt lộn)",
        "doner kebab",
        "bánh giò",
        "lẩu thái 38 trần phú",
        "lẩu ếch",
        "phở thanh hà",
        "nầm nướng",
        "beef steak hòe nhai",
        "phở trộn ở phở hạnh",
        "cafe trứng cafe giảng",
        "kem tràng tiền",
        "viki ô long matcha 38 trần đại nghĩa",
        "cà phê cốt dừa đặng văn ngữ",
        "xôi bà thu 57 thợ nhuộm",
        "bún ngon đặng văn ngữ",
        "bánh cuốn cao bằng",
        "cơm gà hải nam",
        "cháo ếch singapore",
        "bánh mì dân tổ",
        "sà bì chưởng anh độ",
        "bánh tẻ",
        "gà không lối thoát",
        "nem cua bể",
        "kem xôi cầu giấy",
        "chè phạm ngọc thạch",
        "bánh nhãn",
        "chân gà sả tắc",
        "chân gà sốt thái",
        "hàu phô mai",
        "lòng / cháo lòng",
        "bánh đa hến",
        "tôm hùm phô mai bỏ lò",
        "trứng non (cục trắng trắng)",
        "na & vú sữa",
        "kẹo meiji",
        "bánh mì quỳnh hoa",
        "bánh mì nem khoai kim liên",
        "viên hải sản phô mai",
        "nem chua rán",
        "súp lươn & bánh bèo nghệ an, bún trước cửa nhà, bánh canh",
        "xôi hàng bài",
        "thịt xiên nướng quang trung",
        "hải sản thọ phương",
        "buffet bánh tráng nướng dài 2m",
        "bún bò huế ngự uyển",
        "bún đậu mắm tôm",
        "trà sữa khoai môn",
        "kem bơ",
        "hương bơ dừa 135 lò đúc",
        "sing chiak nguyễn văn lộc",
        "macaroni sườn bò 135 nguyễn văn tuyết (trung liệt)",
        "xôi chim 103h7 thành công",
        "bánh mì nướng muối ớt 102 phạm ngọc thạch",
        "miến xào 14 đặng tất",
        "ngan cháy tỏi",
        "kem chanh"
      ]
    },
    {
      "id": "play",
      "emoji": "🎡",
      "name": "Vui chơi",
      "hint": "Đi chơi / trải nghiệm / giải trí",
      "items": [
        "đi gs25",
        "đi xem liveshow",
        "dream games ở royal city",
        "camp vr sbs ở lotte department store",
        "amazing town ở mipec long biên",
        "đi chụp ảnh photobooth",
        "hanoi super karting (công viên yên sở) hoặc vs racing (aeon mall hà đông)",
        "kangji archery ở 88 nguyễn lương bằng",
        "hội chợ giáng sinh ở long biên",
        "vinpearl thủy cung",
        "gắp thú",
        "đi sở thú",
        "làm vòng vĩnh cửu ở dotdotgem nguyễn phong sắc",
        "đi uniqlo",
        "đi mua blindbox",
        "đi cà phê đường tàu",
        "đi escape room miss terry",
        "chợ hoa quảng an",
        "trượt nhà phao ở âu cơ"
      ]
    },
    {
      "id": "self",
      "emoji": "💅",
      "name": "Làm đẹp & sức khoẻ",
      "hint": "Tóc – nail – spa – răng…",
      "items": [
        "làm tóc",
        "cắt tóc",
        "triệt đường chân tóc",
        "đi spa",
        "làm nail",
        "gội đầu dưỡng sinh đi mát xa",
        "khử thâm môi",
        "triệt nách",
        "đi lấy cao răng"
      ]
    },
    {
      "id": "shop",
      "emoji": "🛍️",
      "name": "Mua sắm",
      "hint": "Quần áo, blindbox, quà",
      "items": [
        "đi mua quần áo",
        "đi uniqlo",
        "mua blindbox",
        "mua kẹo meiji"
      ]
    }
  ]
};
